### ISSUE TITLE
群发 ios 推送有失败的可能

### ISSUE THREAD

**Issue by flypiggy** [GeekPark/gpk_account#168]
#164 #这个 broadcast job 写法不对. @Zkuns 
如果要批量广播的话, 设备多的话每次打开 apple 的 apn 连接会被认为是 ddos 攻击.
应该保持一个连接完成推送.
参考[Persistent Connections](persistent-connections)

**Comment by Zkuns** [comment]
我以为创建了APN就是建立了链接，原来每次发送都会重新建立会话，等我更新完xcode就改

**Comment by Zkuns** [comment]
自己维护socket连接，不会每次发送都会重新打开连接了
